version: '3.3'
services:
  redis:
    image: redis:7.0-rc1-alpine
    volumes:
     - ../db/redis-db:/data
    command: 'redis-server --save 60 1 --loglevel warning'
    restart: always
  postgre:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: level-bot
      PGDATA: /var/lib/postgresql/data/level-bot
    volumes:
      - ../db/postgre:/var/lib/postgresql/level-bot
  bot:
    build: .
    restart: always
    links:
      - "redis:redis"
      - "postgre:postgre"