version: '3.3'
services:
  redis:
    image: redis:7.0-rc1-alpine
    volumes:
     - ../db/redis-db:/data
    command: 'redis-server --save 60 1 --loglevel warning'
  bot:
    build: .
    links:
      - "redis:database"